piskoviste/pisek

pisek/compile.py
pisek/program.py

Pitfall je, že existují krajní situace, kdy je něco potřeba
překompilovat, i když je zdroják starší než binárka – třeba když
builduji s debugovacími CFLAGY, ale binárka je release.

Přidána podpora pro kompilaci, jen když došlo ke změně (#13)

---

fixtures/soucet_kasiopea/judge.cpp
fixtures/soucet_kasiopea/judge_bad.cpp
pisek/__main__.py
pisek/compile.py
pisek/judge.py
pisek/program.py
pisek/self_tests/test_kasiopea.py
pisek/self_tests/util.py
pisek/tests/cms_test_suite.py
pisek/tests/kasiopea_test_suite.py

Přidat podporu pro judge v Kasiopeji + základní self-testy.

Kasiopea judge

---

pisek/compile.py
pisek/self_tests/test_kasiopea.py

Resolves #48
Snad to funguje. Nějak zápasím s tím, jak spustit tenhle development písek ve skutečné složce s úlohou, když mám nainstalovanou i produkční verzi. A ten unit test není moc užitečný, protože v něm neumím zkontrolovat *s jakou* chybou to spadlo.

Resolves #48

---

pisek/task_config.py

…takže člověk může napsat `print(config)` a dostane užitečné info.

TaskConfig: přidány  `__repr__` pro snažší vývoj

---

pisek/generator.py
pisek/tests/kasiopea_test_suite.py
pisek/tests/test_case.py

Přehlednější chybová hláška v případě, že neexistují sample testy.

Lepší chybová hláška

---

pisek/compile.py

Přidat podporu pro 'pypy3' Python interpreter

---

pisek/__main__.py
pisek/tests/cms_test_suite.py
pisek/tests/kasiopea_test_suite.py

Není opakovaně nutné pouštět checker, když trvá 5 minut než doběhne.

Argument --no-checker fixes #102

---

fixtures/guess/src/judge.cpp
pisek/jobs/parts/judge.py
pisek/jobs/parts/solution.py

Currently, communication tasks in CMS mode use a custom interface to communicate with the manager.
This PR changes brings the interface in sync with CMS.

Use CMS communication manager interface

---

pisek/env/env.py
pisek/jobs/cache.py
pisek/jobs/jobs.py
pisek/jobs/parts/checker.py
pisek/jobs/parts/compile.py
pisek/jobs/parts/data.py
pisek/jobs/parts/generator.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/program.py
pisek/jobs/parts/solution.py
pisek/jobs/parts/task_job.py
pisek/jobs/parts/testing_log.py
pisek/jobs/parts/tools.py
pisek/paths.py
pisek/server.py
pisek/utils/pipeline_tools.py

Simplified TaskPaths and get rid of task_dir

---

pisek/__main__.py
pisek/env/env.py
pisek/jobs/job_pipeline.py
pisek/jobs/jobs.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/solution.py
pisek/jobs/parts/solution_result.py
pisek/jobs/status.py
pisek/utils/terminal.py
pisek/utils/text.py

Verbose mode

---

pisek/__main__.py
pisek/cms/dataset.py
pisek/cms/submission.py
pisek/cms/testcase.py
pisek/env/env.py
pisek/jobs/cache.py
pisek/jobs/jobs.py
pisek/jobs/parts/chaos_monkey.py
pisek/jobs/parts/checker.py
pisek/jobs/parts/compile.py
pisek/jobs/parts/data.py
pisek/jobs/parts/generator.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/program.py
pisek/jobs/parts/run_result.py
pisek/jobs/parts/solution.py
pisek/jobs/parts/solution_result.py
pisek/jobs/parts/task_job.py
pisek/jobs/parts/testing_log.py
pisek/jobs/parts/tools.py
pisek/server.py
pisek/utils/paths.py
pisek/utils/terminal.py
tests/test_cms.py

Makes reports more reasonable.
Fixes #148, #149

Improve message on solution resulting unexpectedly

---

config-v3-documentation
fixtures/guess/config
pisek/cms/dataset.py
pisek/config/cms-defaults
pisek/config/config_types.py
pisek/config/kasiopea-defaults
pisek/config/task_config.py
pisek/jobs/parts/judge.py

Separated judge calling and judging convention from ``contest_type``.

Judge type

---

config-v3-documentation

ConfigDocs: Document in/out_format

---

pisek/jobs/parts/completeness_check.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/solution.py
pisek/jobs/task_pipeline.py

CompletenessCheck: Add no redundant lines in CMS judge check

---

README.md
pisek/__main__.py
tests/test_cli.py

Rework CLI

---

README.md
fixtures/odd_stub/config
fixtures/odd_stub/gen.py
pisek/config/config_types.py
pisek/license.py
pisek/task_jobs/generator/base_classes.py
pisek/task_jobs/generator/manager.py
pisek/task_jobs/generator/opendata_v1.py
pisek/task_jobs/generator/pisek_gen_v1.py
pisek/task_jobs/task_job.py
pyproject.toml

Pisek Gen V1

---

config-v3-documentation
fixtures/guess/config
pisek/config/cms-defaults
pisek/config/config-description
pisek/config/config-v3-documentation
pisek/config/config_hierarchy.py
pisek/config/config_types.py
pisek/config/did_you_mean.py
pisek/config/task_config.py
pisek/config/update_config.py
pisek/task_jobs/completeness_check.py
pisek/task_jobs/judge.py
pyproject.toml

Did you mean

---

config-v3-documentation
docs/generator.md
fixtures/odd_stub/config
pisek/config/config_types.py
pisek/task_jobs/generator/base_classes.py
pisek/task_jobs/generator/manager.py
pisek/task_jobs/generator/pisek_gen_v1.py
pisek/task_jobs/generator/pisek_v1.py
pisek/task_jobs/program.py

Fixes #204, fixes #205, fixes #206

PisekV1 generator fixing

---

pisek/config/config_errors.py
pisek/config/config_hierarchy.py
pisek/config/task_config.py

Show nice messages for invalid configs

Improve config parsing

---

pisek/task_jobs/judge.py

This should help with the future implementation of the Opendata-V2 judge.

Opendata-V1: abstract judge

---

pisek/task_jobs/generator/pisek_v1.py

PisekV1: disallow input repetition

---

pisek/cms/submission.py

CMS: Include name of submitted solution in comment 

---

pisek/__main__.py

CMS: Make subcommand required

---

pisek/env/base_env.py
pisek/jobs/cache.py
pisek/jobs/job_pipeline.py
pisek/jobs/jobs.py

Instead of clonning env objects, we just save and clear accesses at right times.
We get up to 2x speed improvement on fully cached tasks :tada:

Env: Speed improvements

---

pisek/jobs/cache.py
pisek/jobs/job_pipeline.py
pisek/task_jobs/generator/input_info.py

Add cache versioning and some internal cleanup

Cache improvements

---

pisek/__main__.py
pisek/cms/result.py
pisek/config/config_hierarchy.py
pisek/config/task_config.py
pisek/config/update_config.py
pisek/env/env.py
pisek/jobs/cache.py
pisek/jobs/jobs.py
pisek/jobs/status.py
pisek/task_jobs/checker.py
pisek/task_jobs/generator/pisek_v1.py
pisek/task_jobs/solution/manager.py
pisek/task_jobs/task_job.py
pisek/utils/colors.py
pisek/utils/paths.py
pisek/utils/terminal.py
pisek/utils/text.py
pisek/visualize.py

Fixes #194 
Now we store whether to print colors in `ColorSettings` object.

Color rework

---

pisek/task_jobs/judge.py
pisek/task_jobs/solution/solution_result.py

Verdict messages

---

pisek/task_jobs/generator/manager.py

Generator: Make `GeneratorRespectsSeed` seed choice deterministic

---

docs/batch_judge.md
fixtures/sum_kasiopea/judge_py.py
pisek/task_jobs/generator/base_classes.py
pisek/task_jobs/generator/manager.py
pisek/task_jobs/generator/opendata_v1.py
pisek/task_jobs/generator/pisek_v1.py
pisek/task_jobs/judge.py
pisek/task_jobs/solution/manager.py

Give `-` as seed to judge if input doesn't have seed

---

config-v2-documentation
config-v3-documentation
pisek/config/global-defaults

The documentation currently doesn't specify the default for each key. This PR fixes that.

Docs: Document defaults consistently

---

docs/config-v2-documentation
docs/config-v3-documentation
fixtures/guess/.gitignore
fixtures/odd_stub/.gitignore
fixtures/sum_cms/.gitignore
fixtures/sum_kasiopea/.gitignore
pisek/config/cms-defaults
pisek/config/config-description
pisek/config/global-defaults
pisek/config/kasiopea-defaults
pisek/config/task_config.py
pisek/config/update_config.py
pisek/utils/paths.py
pisek/utils/util.py
tests/test_cms.py
tests/util.py

Remove support for configurable name of `data_subdir` as it is not really necesarry.

Config: Remove data_subdir

---

pisek/task_jobs/generator/manager.py

TestcaseManager: Vary seeds between testcases

---

pisek/task_jobs/task_job.py

LinkData: Follow symlinks

---

pisek/task_jobs/judge.py

TaskJob: Don't pass files to CMS judge it didn't request

---

pisek/jobs/job_pipeline.py
pisek/jobs/jobs.py
pisek/jobs/task_pipeline.py

Clean non relevant files

---

pisek/cms/__init__.py
pisek/cms/dataset.py
pisek/cms/task.py
pisek/config/task_config.py
pisek/jobs/jobs.py
pisek/jobs/task_pipeline.py
pisek/task_jobs/checker.py
pisek/task_jobs/data/data.py
pisek/task_jobs/data/manager.py
pisek/task_jobs/data/testcase_info.py
pisek/task_jobs/generator/cms_old.py
pisek/task_jobs/generator/manager.py
pisek/task_jobs/generator/opendata_v1.py
pisek/task_jobs/generator/pisek_v1.py
pisek/task_jobs/judge.py
pisek/task_jobs/program.py
pisek/task_jobs/solution/manager.py
pisek/task_jobs/solution/solution.py
pisek/task_jobs/task_job.py
pisek/task_jobs/task_manager.py
pisek/task_jobs/tools.py
pisek/utils/paths.py

Tests folder layout

---

pisek/utils/pipeline_tools.py

Just a small improvement when running multiple times

Show run number

---

pisek/task_jobs/solution/manager.py

Added missing prerequisites. Otherwise user would get a bunch of python errors in certain circumstances.

Solution: Fix prerequisites

---

docs/config-v3-documentation

This PR makes two small documentation improvements.

ConfigDocs: Fix some issues pointed out by Martin Mareš

---

docs/CMS.md
docs/batch_judge.md
docs/communication_judge.md
docs/config-v2-documentation
docs/config-v3-documentation
docs/generator.md
pisek/__main__.py

Various documentation improvements.

Docs fixing

---

docs/config-v3-documentation
pisek/config/cms-defaults
pisek/config/config-description
pisek/config/kasiopea-defaults

Fixes #289 
This should be only documentation / defaulting issue.

Config: [all_solutions] source -> run

---

docs/config-v2-documentation
docs/config-v3-documentation

ConfigDocs: Document default values of execution limits

---

pisek/jobs/jobs.py

Jobs: KeyError can happen too

---

pisek/task_jobs/data/data.py
pisek/task_jobs/tools.py

Tools+Data: Make job names unique

---

pisek/utils/util.py

This improves caching in cases when you test solution and then test the whole task.

Util: Clean only accessed dirs

---

pisek/task_jobs/generator/manager.py

Validate: Run validator on all tests including testcase

---

pisek/cms/dataset.py

CMS: Verify config can be translated to CMS settings before importing

---

pisek/__main__.py
pisek/env/env.py
pisek/task_jobs/program.py
pisek/visualize.py
tests/test_cli.py
tests/util.py

Env: timeout -> time-limit

---

pisek/jobs/cache.py

Fixes EOFError after pisek is killed in the middle of cache dump.

Cache: Swap cache file when completed

---

docs/CMS.md

Docs: Remove mentions of removed limitations when checking the results of CMS submissions

---

docs/config-v3-documentation
docs/validator.md
fixtures/max/config
fixtures/max/validate.py
pisek/config/cms-defaults
pisek/config/config-description
pisek/config/config_description.py
pisek/config/config_types.py
pisek/config/global-defaults
pisek/config/kasiopea-defaults
pisek/config/task_config.py
pisek/task_jobs/generator/generator_manager.py
pisek/task_jobs/validator/simple_validator.py
pisek/task_jobs/validator/validator_base.py
pisek/task_jobs/validator/validators.py

Adds a validator type that returns with code 42 on successful validation.
Fixes #381

Add simple-42 validator

---

docs/config-v2-documentation
docs/config-v3-documentation
fixtures/odd_stub/config
fixtures/sum_cms/config
fixtures/sum_cms/validate.py
fixtures/sum_cms/validate_strict.py
fixtures/sum_kasiopea/config
fixtures/sum_kasiopea/validate.py
fixtures/sum_kasiopea/validate_strict.py
pisek/config/config-description
pisek/config/task_config.py
pisek/config/update_config.py
tests/test_cms.py
tests/test_kasiopea.py
tests/util.py

Removes experimental status from config v3.
Fixes #383

Finalize config-v3

---

examples/organization-configs/README.md
examples/organization-configs/cms-base-v1
examples/organization-configs/cms-batch-v1
examples/organization-configs/cms-communication-v1
examples/organization-configs/opendata-v1

docs(examples): Add example organization configs

---

docs/config-v2-documentation
docs/config-v3-documentation
pisek/config/config_types.py

feat(cms): support oi_restricted feedback level

---

pyproject.toml

fix(pyproject): Update homepage & issues urls

---

pisek/task_jobs/builder/build.py
pisek/task_jobs/builder/strategies.py

fix(build): Make builds run in parallel

---

examples/cms-batch/config

fix(examples): Fix points in cms-batch task

---

pisek/task_jobs/checker/judgelib_checker.py
pisek/task_jobs/program.py
pisek/task_jobs/tools.py

fix(tools): Make internal tools start with an underscore
