pisek/generator.py
pisek/judge.py
pisek/program.py
pisek/task_config.py
pisek/util.py

Přidal jsem typové anotace základní knihovny (tj. mimo podložky `tests/` a souboru `main.py`) tak,
aby byl MyPy spokojen i na `--strict` úrovni.
Zároveň jsem poupravil kousky stávajících castů a anotacích, které byly nesprávné/nedostatečné/zvláštní.
Funkčnost jsem netestoval, nechám to na self-testech přes GitHub CI. ¯\\\_(ツ)_/¯
Prosím o zběžnou kontrolu, @RichardHladik nebo @IAmWave.

Přidat lepší typové anotace

---

pisek/self_tests/util.py
pisek/tests/cms_test_suite.py
pisek/tests/kasiopea_test_suite.py
pisek/tests/test_case.py

Při testování CMS test suite Písek pro každé řešení vypíše za každý test
jeden znak značící, jestli test prošel/neprošel, popř. jaký byl jeho
verdikt.
Work in progress. Teď to plevelí výpis self-testů, chtělo by to asi rozlišovat, jestli se testují self-testy, nebo někdo zavolal Písek interaktivně a chce vidět výsledky testů / popř. nějaký command-line switch.

Detailnější výpis jednotlivých testů

---

fixtures/soucet_kasiopea/judge_bad_whitespace.py
fixtures/soucet_kasiopea/judge_py.py
pisek/judge.py
pisek/self_tests/test_kasiopea.py
pisek/tests/kasiopea_test_suite.py

Metoda: přidat mezery a změnit `\n -> \r\n` v řešení účastníka a vzorovém výstupu. Judge by měl i po těchto úpravách mít stejný verdikt.

Kontrolovat, jestli judge správně řeší whitespace a CRLF

---

pisek/compile.py

Vzhledem k migraci úloh Kasiopei na nový web jsem objevil a opravil pár nedostatků v úlohách.
* Nastavil jsem, že se standardně pro C/C++ linkuje `-lm` (`<cmath>`/`math.h`)
* Přidal jsem podporu pro úlohy psané v Free Pascalu -- umíme je nyní zkompilovat.
U druhého bodu bychom ale měli zvážit issue https://github.com/kasiopea-org/pisek/issues/52.

Vylepšit podporu pro Kasiopeu

---

fixtures/soucet_cms/check.py
fixtures/soucet_cms/check_loose.py
fixtures/soucet_cms/check_strict.py
fixtures/soucet_cms/config
fixtures/soucet_kasiopea/check.py
fixtures/soucet_kasiopea/check_loose.py
fixtures/soucet_kasiopea/check_strict.py
fixtures/soucet_kasiopea/config
pisek/checker.py
pisek/self_tests/test_cms.py
pisek/self_tests/test_kasiopea.py
pisek/task_config.py
pisek/tests/cms_test_suite.py
pisek/tests/kasiopea_test_suite.py
pisek/tests/test_case.py

Dva nové testy pro checkery:
- `InputsPassChecker` spustí checker na vygenerované vstupy a zkontroluje, že projde.
- `CheckerDistinguishesSubtasks` je tu proto, aby neprošel checker, který vždycky vrátí returncode 0. Zkontroluje, že kdybychom do subtasku `i` přidali testy ze subtasku `i+1`, checker si bude stěžovat.
Taky jsem přidal odpovídající self-testy, jak pro Kasiopeu tak pro CMS.
Do budoucna bych zvážil, jestli `get_subtasks` nedát do `TaskConfigu` a `in_self_tests` taky.
Resolves #5

Podpora pro checkery

---

pisek/generator.py
pisek/self_tests/test_cms.py
pisek/self_tests/util.py
pisek/solution.py
pisek/tests/cms_test_suite.py
pisek/tests/kasiopea_test_suite.py
pisek/tests/test_case.py

Jednoduchá změna, ale _hodně_ zrychluje workflow. Takhle už se bude cachovat vše pomalé, takže po prvním runu trvajícím asi 2 minuty dostaneme při druhém spuštění:
```
Testuji úlohu vyberko/2021/d1/stepan
Upozornění: v configu není specifikovaný checker. Vygenerované vstupy tudíž nejsou zkontrolované. Doporučujeme proto nastavit v sekci [tests] pole `checker`.
Generátor geninputs funguje ...
Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.
ok
Řešení solutions/opt získá 10b ... ····|························|············|··············|················| ok
Řešení solutions/wrong_0b získá 0b ... |W|W|W|W| ok
Řešení solutions/hranynulawrong_0b získá 0b ... |····W|W|W|W| ok
Řešení solutions/hranynula_3b získá 3b ... |························|W|W|W| ok
Řešení …
```

Vracet cachované .out soubory vytvořené řešeními

---

.github/workflows/python_pisek_tester.yml
pisek/__main__.py
pisek/judge.py
pisek/program.py
pisek/solution.py
pisek/tests/kasiopea_test_suite.py
pisek/tests/test_case.py
setup.py

Resolves #20 and #44
Enum `RunResult` jsem přejmenoval na `RunResultKind` a `Verdict` na původní `RunResult` - je to prostě `RunResultKind` + optional chybová hláška. `Verdict` bylo beztak trochu matoucí, protože to nemá s judgem nic společného (jak jsem si myslel #44).
Všechny funkce v `program.py` teď vrací nový `RunResult`. Díky tomu lze propagovat chybovou hlášku až k testům a tam ji vypsat.
Ukázka výstupu:
```
Testuji řešení: solve
Běží generátor: 100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1569.14it/s]
Generátor se nezměnil, používám vstupy vygenerované v předchozím běhu.
ok
Judge správně řeší whitespace a konce řádku ... ok
Řešení solve získá 10b ... ·|·|!| FAIL …
```

Vypsat chybovou hlášku při runtime erroru řešení

---

pisek/compile.py

Kasiopea používá by-default C++17 a C17 standard a některé úlohy z minulého roku na tomto nastavení závisí.
Tato PR nastavuje vlajku `std=c++17` při kompilaci C++ a vlajku `std=c17` při kompilaci C.

Kompilovat C++17 a C17 by-default

---

example-config
fixtures/soucet_cms/config
pisek/tests/cms_test_suite.py

Nyní ``sec_solve_time_limit`` defaultuje na ``solve_time_limit`` a není to v configu zapotřebí psát dvakrát.

sec_solve_time_limit defaultuje na solve_time_limit fixes #76

---

pisek/jobs/jobs.py
pisek/jobs/parts/chaos_monkey.py
pisek/jobs/parts/checker.py
pisek/jobs/parts/compile.py
pisek/jobs/parts/data.py
pisek/jobs/parts/generator.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/program.py
pisek/jobs/parts/solution.py
pisek/jobs/parts/task_job.py
pisek/jobs/parts/testing_log.py
pisek/jobs/parts/tools.py
pisek/paths.py
pisek/self_tests/test_cms.py
pisek/visualize.py

Rewrote how we represent paths. Now instead of path string we have ``TaskPath`` instance that contains:
- Full path (for file operations)
- Path relative to task directory (for failures)
- Basename (for job names)
This way we can always choose which form we want to show instead of constant transformations

Redo paths

---

pisek/__main__.py
pisek/cms/dataset.py

This PR allows you to omit the `-d`/`--dataset` flag for selecting a dataset when there is only one dataset.
When there are multiple datasets, it will also print their descriptions, allowing you to copy one of them.
This makes it way easier to use `check` and `testing-log`.

CMS: Make -d default to the only dataset

---

pisek/jobs/jobs.py
pisek/jobs/parts/testing_log.py

Generalized job core for `Job`s running always. `JobManger`s have to generate result even if `JobManager._evaluate` fails.
Fixes #152.

Generate testing log even if solution fails

---

fixtures/sum_cms/gen_no_lf.py
fixtures/sum_cms/solve_no_lf.py
fixtures/sum_kasiopea/config
pisek/config/config_types.py
pisek/config/global-defaults
pisek/config/task_config.py
pisek/config/update_config.py
pisek/jobs/parts/data.py
tests/test_cms.py
tests/test_kasiopea.py

Adds support for the `in_format` and `out_format` keys, which can be set to `text` or `binary`. Setting the correct key to `binary` will stop pisek from checking if the relevant files are UNIX text files and contain valid ASCII chars.
Resolves #169.

DataChecking: Support in_format and out_format keys

---

config-v3-documentation
fixtures/guess/config
pisek/config/cms-defaults
pisek/config/global-defaults
pisek/config/kasiopea-defaults
pisek/config/task_config.py
pisek/config/update_config.py

Moves the `stub` and `headers` keys for `[tests]` to `[all_solutions]`.
Resolved #171.

TaskConfig: Move `stub` and `headers` to `all_solutions`

---

config-v2-documentation
config-v3-documentation
fixtures/sum_kasiopea/config
pisek/config/config_types.py
pisek/config/global-defaults
pisek/config/task_config.py
pisek/jobs/parts/judge.py
pisek/jobs/parts/tools.py
pisek/tools/judgelib/io.cc
pisek/tools/judgelib/judge-token.cc
pisek/tools/judgelib/judge.h
pisek/tools/judgelib/random.cc
pisek/tools/judgelib/token.cc
pisek/tools/judgelib/util.cc
pyproject.toml

This PR imports KSP's `judgelib` judge utility library along with the `judge-token` program. It also adds support for using it instead of `diff`.
Both `out_check=diff` and `out_check=tokens` are supported. If we wan't to deprecate `diff` or alias it to `tokens`, we can easily do so in the future. It also supports all options supported by KSP's opendata tool.
One slight difference between this and KSP's implementation is that the floating point mode is disabled by setting `tokens_float_rel_error` and `tokens_float_abs_error` to `X` instead of the empty string.
Closes #173.

Add support for faster whitespace tolerant judge

---

pisek/cms/testcase.py

Currently, the CMS importer will only search the static input directory for samples only. This PR makes it search for each input glob in both the static directory and the directory with generated inputs.

Add support for non-sample static tests

---

fixtures/guess/config
fixtures/odd_stub/config
fixtures/sum_cms/config
fixtures/sum_kasiopea/config
pisek/tools/minibox.c
tests/test_cli.py
tests/util.py

Minibox now ends at most tenth of second later then program instead of one second.
Also fixes #34 (a bit). Two seconds/test seem pretty reasonable anyway.

Minibox improvements

---

pisek/cms/submission.py

CMS requires all timestamps be in UTC, but SQLAlchemy will convert them to local time if they are timezone aware. 
Fixes #233

CMS: Fix time of submission timezone compatibility

---

pisek/__main__.py
pisek/cms/__init__.py
pisek/cms/dataset.py

This PR adds a flag named `--active-dataset` (or just `-a`) that allows the user to select the active dataset for `cms check` or `cms testing-log` without having to remember its name. 
Somewhat fixes #182

CMS: Add flag -a to act on active dataset

---

pisek/visualize.py

I catch the error when trying to visualize without a testing log, explain the need to test with `--testing-log`.
Addresses #256.

Handle missing testing log

---

pisek/config/config_description.py
pisek/config/config_hierarchy.py

1. Now checks keys according to `config-description` and not to their usage. This allows keys to be overshadowed by other keys.
2. Improved error messages for context-specific keys.
3. Made key recommendations more predictable. It can now recommend key that is not allowed in this context, but in such cases you probably need to look up config documentation anyway.

ConfigDescription: Change checking unused keys

---

docs/config-v3-documentation

Remove solution_subdir from documentation as it was replaces by `[run_solution] subdir`

ConfigDocs: Remove solutions_subdir

---

pisek/utils/pipeline_tools.py

PipelineTools: Create directory for lock if not present

---

.vscode/launch.json
fixtures/guess/config
pisek/config/task_config.py
pisek/task_jobs/generator/manager.py
pisek/task_jobs/solution/manager.py
pisek/task_jobs/solution/solution.py

When inputs overlap between tests by using `in_globs` directly (and not predeccessors), it could lead to wrong cancelations and testing logs.

Solution: Fix overlapping inputs

---

pisek/task_jobs/data/manager.py

Fixes the error message that's shown when a sample input isn't static to include the name of that input, instead of the last input globally.

Data: Report proper name of generated sample in error message

---

pisek/task_jobs/tools.py

This PR makes it possible to run a failing solution a second time without running `pisek clean` first.

Tools: Overwrite when linking truncated output

---

pisek/__main__.py
pisek/cms/__init__.py
pisek/cms/dataset.py
pisek/cms/task.py

This PR allows for setting the time limit when importing with a flag:
```
pisek cms create -t 10
```

CMS: Add flag to override time limit

---

pisek/env/env.py

This PR improves the documentation for the timeout attribute in the Env class to clarify its usage and the effect of the timeout value on task testing.
Fixes #341

docs: improve documentation for timeout in Env class

---

pisek/task_jobs/solution/manager.py

When running with `judge_needs_out=0`, `-C` and solution doesn't result as expected, pisek crashes:
```
[...]
File "/home/skipy/dev/pisek/pisek/task_jobs/solution/manager.py", line 497, in as_expected
msg += f"\n{tab(breaker.message())}"
~~~~~~~~~~~~~~~^^
File "/home/skipy/dev/pisek/pisek/task_jobs/checker/checker_base.py", line 116, in message
text += f"correct output: {self._quote_file_with_name(self.correct_output)}"
~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
File "/home/skipy/dev/pisek/pisek/task_jobs/task_job.py", line 252, in _quote_file_with_name
return f"{file.col(self._env)}\n{self._colored(tab(self._quote_file(file, **kwargs)), 'yellow')}\n"
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
File "/home/skipy/dev/pisek/pisek/task_jobs/task_job.py", line 241, in _quote_file
with …
```

fix(solution): Fix missing correct solution when judge_needs_out=0 and -C

---

pisek/env/base_env.py

This further optimizes BaseEnv by avoiding the overloaded `__getattribute__` method.

perf(env): Optimizations

---

docs/config-v3-documentation
pisek/config/config_types.py
pisek/config/task_config.py
pisek/config/update_config.py
pisek/task_jobs/checker/cms_judge.py
pisek/task_jobs/checker/opendata_judge.py
pisek/task_jobs/generator/cms_old.py
pisek/task_jobs/generator/opendata_v1.py
pisek/task_jobs/generator/pisek_v1.py
pisek/task_jobs/program.py
pisek/task_jobs/solution/solution.py
pisek/task_jobs/validator/validator_base.py

Changes `ProgramType` to `ProgramRole`. Reasons for this change:
- type -> `(gen|validator|judge)_type`, role -> `ProgramRole`
- Also programs can have multiple roles

refactor: ProgramType -> ProgramRole
